# Generated by Django 3.1 on 2020-10-31 05:28

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200912_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='1.', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], inverse_match=False, message='Поставьте точку в конце!', regex='\\.$')], verbose_name='title'),
            preserve_default=False,
        ),
    ]
