# Generated by Django 3.1 on 2020-10-31 05:39

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.EmailValidator(message='Введите корректный email', whitelist=['localhost', 'my_local'])], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='Поставьте точку в конце!', regex='\\.$')], verbose_name='title'),
        ),
    ]
