# Generated by Django 3.1 on 2020-10-31 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201031_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.URLValidator(message='Введите корректный URL', schemes=['https'])], verbose_name='url'),
        ),
    ]
