# Generated by Django 3.1 on 2020-10-31 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_int_list_sep'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interval_value',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=42, message='Не более 42'), django.core.validators.MinValueValidator(limit_value=9, message='е менее 9')], verbose_name='interval'),
        ),
    ]
