# Generated by Django 3.1 on 2020-10-31 09:23

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[blog.models.validate_date_of_birth], verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='file/', validators=[django.core.validators.validate_image_file_extension], verbose_name='file'),
        ),
    ]
